## To encourage contributors to use issue templates, we don't allow blank issues
blank_issues_enabled: false

contact_links:
  - name: "\u2753 Slack Community of Sinuos"
    url: 'https://slack.com/sinuoslabs'
    about: 'Please ask support questions or discuss suggestions/enhancements here.'
